import { useCallback, useEffect, useState, type FormEvent } from "react";
import { db, errorMessage, type Row } from "@quicksort/candidate-db";
import { Heading, Notice, Pill, Empty, formatDate } from "@quicksort/candidate-ui";
export function AccessManager(){
 const [requests,setRequests]=useState<Row<"admin_access_requests">[]>([]),[profiles,setProfiles]=useState<Row<"profiles">[]>([]),[roles,setRoles]=useState<Row<"user_roles">[]>([]),[owners,setOwners]=useState<Row<"portal_owners">[]>([]),[audit,setAudit]=useState<Row<"admin_access_audit">[]>([]);
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [confirmation,setConfirmation]=useState<{email:string;decision:string}|null>(null);
 const load=useCallback(async()=>{
  try{const results=await Promise.all([db().from("admin_access_requests").select("*").order("created_at",{ascending:false}),db().from("profiles").select("*"),db().from("user_roles").select("*"),db().from("portal_owners").select("*"),db().from("admin_access_audit").select("*").order("created_at",{ascending:false}).limit(50)]);
  for(const r of results)if(r.error)throw r.error;
  setRequests(results[0].data||[]);setProfiles(results[1].data||[]);setRoles(results[2].data||[]);setOwners(results[3].data||[]);setAudit(results[4].data||[]);
  }catch(e){setError(errorMessage(e))}finally{setLoading(false)}
 },[]);
 useEffect(()=>{void load()},[load]);
 const email=(id:string)=>profiles.find(p=>p.id===id)?.email||id;
 async function decide(){if(!confirmation)return;setBusy(true);setError("");setMessage("");try{const {error}=await db().rpc("review_admin_access",{target_email:confirmation.email,decision:confirmation.decision});if(error)throw error;setMessage(`Access ${confirmation.decision} for ${confirmation.email}.`);setConfirmation(null);await load()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 function grant(e:FormEvent<HTMLFormElement>){e.preventDefault();setConfirmation({email:String(new FormData(e.currentTarget).get("email")).trim(),decision:"approved"})}
 return <><Heading eyebrow="Owner workspace" title="Admin access">You and your founder decide who can manage Quicksort. Signing in never grants admin access automatically.</Heading><Notice error>{error}</Notice><Notice>{message}</Notice>
 {confirmation&&<section className="panel" aria-label="Confirm access change"><h2>Confirm access change</h2><p><strong>{confirmation.email}</strong> will have their admin access <strong>{confirmation.decision}</strong>.</p><div className="actions"><button className="btn" disabled={busy} onClick={decide}>Confirm {confirmation.decision === "approved" ? "approval" : confirmation.decision === "revoked" ? "revocation" : "rejection"}</button><button className="btn secondary" disabled={busy} onClick={()=>setConfirmation(null)}>Cancel</button></div></section>}
 <section className="panel"><h2>Approve an existing account</h2><p className="muted">Ask the person to sign in first, then enter their verified account email.</p><form className="form" onSubmit={grant}><label>Email address<input name="email" type="email" required placeholder="colleague@quicksort.fr"/></label><div><button className="btn" disabled={busy}>Review approval</button></div></form></section>
 <section className="panel"><div className="panel-head"><h2>Access requests</h2><button className="link-button" onClick={()=>void load()}>Refresh requests</button></div>{loading?<p role="status">Loading access requests…</p>:requests.length===0?<Empty title="No requests yet">People can request admin access after signing in.</Empty>:requests.map(r=><div className="list-row" key={r.user_id}><div><h3>{email(r.user_id)}</h3><Pill status={r.status}/><p className="muted small-text">Requested {formatDate(r.created_at)}</p></div><div className="actions">{r.status!=="approved"&&<button className="btn small" disabled={busy} onClick={()=>setConfirmation({email:email(r.user_id),decision:"approved"})}>Approve</button>}{r.status==="pending"&&<button className="btn secondary small" disabled={busy} onClick={()=>setConfirmation({email:email(r.user_id),decision:"rejected"})}>Reject</button>}</div></div>)}</section>
 <section className="panel"><h2>Current administrators</h2>{roles.filter(r=>r.role==="admin").map(r=><div className="list-row" key={r.user_id}><div><h3>{email(r.user_id)}</h3><Pill status={owners.some(o=>o.user_id===r.user_id)?"owner":"admin"}/></div>{!owners.some(o=>o.user_id===r.user_id)&&<button className="btn danger small" disabled={busy} onClick={()=>setConfirmation({email:email(r.user_id),decision:"revoked"})}>Revoke access</button>}</div>)}<p className="small-text muted">Owner accounts are protected from removal here.</p></section>
 <section className="panel"><h2>Recent access changes</h2>{audit.length===0?<p className="muted">No access changes yet.</p>:audit.map(item=><div className="list-row" key={item.id}><p>{email(item.actor_id)} {item.action} access for {email(item.target_id)}</p><span className="muted small-text">{formatDate(item.created_at)}</span></div>)}</section></>;
}
