module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        "display-md-semibold": "var(--display-md-semibold-font-family)",
        "display-sm-semibold": "var(--display-sm-semibold-font-family)",
        "m3-title-large": "var(--m3-title-large-font-family)",
        "text-lg-semibold": "var(--text-lg-semibold-font-family)",
        "text-md-regular": "var(--text-md-regular-font-family)",
        "text-md-semibold": "var(--text-md-semibold-font-family)",
        "text-xl-regular": "var(--text-xl-regular-font-family)",
        "text-xl-semibold": "var(--text-xl-semibold-font-family)",
        display: ["Hanken Grotesk", "Inter", "Helvetica Neue", "Arial", "sans-serif"],
        mono: ["JetBrains Mono", "SF Mono", "ui-monospace", "monospace"],
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: {
        "backdrop-blurs-backdrop-blur-lg":
          "var(--backdrop-blurs-backdrop-blur-lg)",
        "shadows-shadow-xs": "var(--shadows-shadow-xs)",
        1: "var(--qs-shadow-1)",
        2: "var(--qs-shadow-2)",
        3: "var(--qs-shadow-3)",
      },
      transitionTimingFunction: {
        qs: "var(--qs-ease)",
        "qs-out": "var(--qs-ease-out)",
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        ink: "var(--qs-ink)",
        "ink-2": "var(--qs-ink-2)",
        "rich-black": "var(--qs-rich-black)",
        "dim-gray": "var(--qs-dim-gray)",
        timberwolf: "var(--qs-timberwolf)",
        seasalt: "var(--qs-seasalt)",
        lime: "var(--qs-lime)",
        "fg-1": "var(--qs-fg-1)",
        "fg-2": "var(--qs-fg-2)",
        "fg-3": "var(--qs-fg-3)",
        "fg-4": "var(--qs-fg-4)",
        "fg-inv": "var(--qs-fg-inv)",
        "fg-inv-2": "var(--qs-fg-inv-2)",
        "fg-inv-3": "var(--qs-fg-inv-3)",
        "border-inv": "var(--qs-border-inv)",
        "border-inv-strong": "var(--qs-border-inv-strong)",
        "svc-business": "var(--qs-svc-business)",
        "svc-data": "var(--qs-svc-data)",
        "svc-infra": "var(--qs-svc-infra)",
        "care-purple": "var(--qs-care-purple)",
        "care-pink": "var(--qs-care-pink)",
        "badge-bg": "var(--qs-badge-bg)",
        "badge-border": "var(--qs-badge-border)",
        "badge-dot": "var(--qs-badge-dot)",
        "badge-text": "var(--qs-badge-text)",
      },
      borderRadius: {
        sm: "var(--qs-radius-sm)",
        md: "var(--qs-radius-md)",
        lg: "var(--qs-radius-lg)",
        xl: "var(--qs-radius-xl)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
