alter table public.kanban_projects
  add column if not exists project_number bigint generated by default as identity;

alter table public.kanban_cards
  add column if not exists card_number bigint generated by default as identity;

create unique index if not exists kanban_projects_project_number_key
  on public.kanban_projects (project_number);
create unique index if not exists kanban_cards_card_number_key
  on public.kanban_cards (card_number);

create table if not exists public.kanban_board_accounts (
  board_id uuid not null references public.kanban_boards(id) on delete cascade,
  account_id uuid not null references public.business_accounts(id) on delete cascade,
  created_by uuid default private.current_user_id(),
  created_at timestamptz not null default now(),
  primary key (board_id, account_id)
);

create table if not exists public.kanban_card_contacts (
  card_id uuid not null references public.kanban_cards(id) on delete cascade,
  account_id uuid not null references public.business_accounts(id) on delete cascade,
  contact_key text not null,
  created_by uuid default private.current_user_id(),
  created_at timestamptz not null default now(),
  primary key (card_id, account_id, contact_key)
);

create index if not exists kanban_board_accounts_account_idx
  on public.kanban_board_accounts (account_id);
create index if not exists kanban_board_accounts_creator_idx
  on public.kanban_board_accounts (created_by);
create index if not exists kanban_card_contacts_account_contact_idx
  on public.kanban_card_contacts (account_id, contact_key);
create index if not exists kanban_card_contacts_creator_idx
  on public.kanban_card_contacts (created_by);

alter table public.kanban_board_accounts enable row level security;
alter table public.kanban_card_contacts enable row level security;

drop policy if exists "Admins manage board account links" on public.kanban_board_accounts;
create policy "Admins manage board account links"
  on public.kanban_board_accounts for all to authenticated
  using ((select private.is_admin()))
  with check ((select private.is_admin()));

drop policy if exists "Admins manage card contact links" on public.kanban_card_contacts;
create policy "Admins manage card contact links"
  on public.kanban_card_contacts for all to authenticated
  using ((select private.is_admin()))
  with check ((select private.is_admin()));

revoke all on public.kanban_board_accounts from public, anon, authenticated;
revoke all on public.kanban_card_contacts from public, anon, authenticated;
grant select, insert, delete on public.kanban_board_accounts to authenticated;
grant select, insert, delete on public.kanban_card_contacts to authenticated;
